[WIP] [LM-11579] Adding LMDocument
LikeMindsCommunity/likeminds-chat-flutter pull request #47
Opened 2024-08-29 09:27 UTC by divyanshgandhilm

## Description
Adding PDF documents attachment support

**Features**
- Added LMDocument Widget
- Updated media_utils and screens
- Cleaned up code

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2024-09-09 11:42 UTC, AnujLM requested changes

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/preview.dart
> +/// A widget that displays a document preview with multiple attachments.
```suggestion
/// A widget that displays a document preview with single attachment.
```

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/preview.dart
how will we add customisation here?

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/thumbnail.dart
> +                debugPrint(widget.media.mediaUrl);
remove debugPrint

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/thumbnail.dart
> +                debugPrint(file!.path);
remove debugPrint() and commented code.

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/tile.dart
> +
add titleBuilder

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/tile.dart
> +  final Widget? subtitle;
add subTitleBuilder

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/tile.dart
> +  final LMChatIcon? documentIcon;
add iconBuilder

2024-09-09 11:42 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/shimmers/document_shimmer.dart
> +        baseColor: Colors.black26,
make it customisable, by creating a style class and use here.

2024-09-10 07:21 UTC, divyanshgandhilm commented on lib/packages/ui/lib/src/widgets/media/document/preview.dart
Added style classes for both preview widgets

2024-09-10 07:22 UTC, divyanshgandhilm commented on lib/packages/ui/lib/src/widgets/media/document/tile.dart
> +  final LMChatIcon? documentIcon;
Converted it to widget class

2024-09-10 08:02 UTC, AnujLM approved these changes

2024-09-10 08:03 UTC, merged