[WIP][LM-12816] Remaining bug fixes
LikeMindsCommunity/likeminds-chat-flutter pull request #69
Opened 2024-11-14 05:58 UTC by divyanshgandhilm

## Description
Fixing all remaining bugs from previous releases

**Features**

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fixes a breaking changes)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [ ] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2024-11-29 10:33 UTC, AnujLM requested changes

2024-11-29 10:33 UTC, AnujLM commented on lib/packages/core/lib/src/views/media/media_preview.dart
> +        final String formattedDate =
can we use DateFomate from itl package here?

2024-11-29 10:33 UTC, AnujLM commented on lib/packages/core/lib/src/views/media/media_preview.dart
> +        height: MediaQuery.of(context).size.height,
user `MediaQuery.sizeOf(context).height` for better performance.

2024-11-29 10:33 UTC, AnujLM commented on lib/packages/ui/lib/src/widgets/media/document/preview.dart
> +                //   Column(
remove commented code, if not requried.

2024-12-02 11:22 UTC, divyanshgandhilm commented
Fixed these issues in the next PR

2024-12-02 11:35 UTC, merged